#! /bin/sh

sxhkd &
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 10


my_laptop_external_monitor=$(xrandr --query | grep 'HDMI-1')
if [[ $my_laptop_external_monitor = *connected* ]]; then
	xrandr --output HDMI-1 --primary --mode 1920x1080 --rotate normal --output eDP-1 --mode 1920x1080 --rotate normal --same-as HDMI-1
fi

bspc config border_width         1
bspc config window_gap           1

#bspc config initial_polarity first_child
bspc config focus_follows_pointer true
bspc config split_ratio          0.45
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config normal_border_color  "#424242"
bspc config focused_border_color "#00FFFF"
#bspc window --presel right

bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a '*:albert' focus=on
bspc rule -a '*:unimatrix' state=fullscreen

compton -b &
dunst &
nm-applet &
albert &
unclutter --ignore-scrolling --timeout 2 &
$HOME/.config/polybar/launch.sh

redshift -O 3600
#pscircle --output=./Pictures/pscircle.png --background-color=000000ff
#nitrogen --set-zoom-fill --save ~/Pictures/pscircle.png
