#!/bin/zsh

rsync -avz ~/Documents/.dotfiles/jupyter/startup.ipy ~/.ipython/profile_default/startup

source ~/Documents/.dotfiles/jupyter/.virtual

workon jp

jt -t gruvboxd -fs 110 -altp -tfs 11 -nfs 115 -cellw 100% -T

jupyter-notebook &

disown

exit
