#!/bin/zsh

rsync -avu --delete ~/.zshrc 		~/.dotfiles
rsync -avu --delete ~/.vimrc 		~/.dotfiles
rsync -avu --delete ~/.config/bspwm 	~/.dotfiles
rsync -avu --delete ~/.config/sxhkd 	~/.dotfiles
rsync -avu --delete ~/.config/kitty 	~/.dotfiles
rsync -avu --delete ~/.config/dunst 	~/.dotfiles
rsync -avu --delete ~/.config/zathura 	~/.dotfiles
rsync -avu --delete ~/.config/polybar 	~/.dotfiles
rsync -avu --delete ~/.config/rofi 	~/.dotfiles
rsync -avu --delete ~/.config/albert 	~/.dotfiles


cd ~/.dotfiles

git commit -a -m "update" &&
git add --all &&
git push origin master &&

cd -
